name: Check for updates

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AppJail Central
        uses: actions/checkout@v4
        with:
          path: central

      - name: Checkout FreeBSD Ports (Shallow Clone)
        uses: actions/checkout@v4
        with:
          repository: FreeBSD/FreeBSD-ports
          path: freebsd-ports
          fetch-depth: 1

      - name: Run check-for-updates and capture output
        id: check_updates
        env:
          PORTSDIR: ${{ github.workspace }}/freebsd-ports
        run: |
          cp central/scripts/check-for-updates.sh ./check-updates.sh
          chmod +x ./check-updates.sh

          sed -i 's/find -E /find -regextype posix-extended /g' ./check-updates.sh

          OUTPUT=$(./check-updates.sh 2>&1)
          echo "$OUTPUT" > updates_log.txt

          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          if echo "$OUTPUT" | grep -qE "^[SNn]:"; then
            echo "has_updates=true" >> $GITHUB_OUTPUT
          else
            echo "has_updates=false" >> $GITHUB_OUTPUT
          fi

      - name: Notify via Telegram
        if: steps.check_updates.outputs.has_updates == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.telegram_chat }}
          token: ${{ secrets.telegram_token }}
          format: html
          message: |
            🚨 New versions or missing ports have been found.

            <strong>Details</strong>:
            <code>
            ${{ steps.check_updates.outputs.output }}
            </code>

            🔗 <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Job Details</a>
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@7a9194bad497f0b993708eeaf10fc0a2d726eb71
